ALTER TABLE teacher ADD COLUMN department_id INT NOT NULL;
ALTER TABLE teacher ADD CONSTRAINT department_teacher_fk FOREIGN KEY (department_id) REFERENCES department(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE education_level ADD CONSTRAINT unique_level_name UNIQUE (level_name);
ALTER TABLE education_form ADD CONSTRAINT unique_form_name UNIQUE (form_name);
ALTER TABLE department ADD CONSTRAINT unique_department_name UNIQUE (department_name);
ALTER TABLE faculty ADD CONSTRAINT unique_faculty_name UNIQUE (faculty_name);
ALTER TABLE job_title ADD CONSTRAINT unique_job_name UNIQUE (job_name);
ALTER TABLE mark ADD CONSTRAINT unique_type_mark UNIQUE (type_mark);
ALTER TABLE certification_form ADD CONSTRAINT unique_form_name2 UNIQUE (form_name);
ALTER TABLE teaching_type ADD CONSTRAINT unique_teaching_name UNIQUE (teaching_name);
ALTER TABLE campus ADD CONSTRAINT unique_campus_name UNIQUE (campus_name);
ALTER TABLE campus ADD CONSTRAINT unique_address UNIQUE (address);
ALTER TABLE type_task ADD CONSTRAINT unique_task_name UNIQUE (task_name);